### ISSUE TITLE
The value of variable isHit is always false.

### ISSUE THREAD

**Issue by zhouxinan** [hungweitseng/CS203-fa21-prefetcher#1]
In the following code line, the value of variable isHit is always false, because in each iteration, `isHit = false;`. So there must be some logic errors.

https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/3aeaf3e513581b11fac03b5767d8405b5bec10f1/main.C#L123

**Comment by hungweitseng** [comment]
isHit will be set to true in cache.C.

**Comment by zhouxinan** [comment]
isHit will be set to true in cache.C. -- It's true, but it will have no persistence.
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/3aeaf3e513581b11fac03b5767d8405b5bec10f1/main.C#L85
The above line will reset isHit to false for each iteration.

**Comment by hungweitseng** [comment]
That is also expected -- we serve each request in serial in the simulator and it's supposed to reset everytime later.

**Comment by zhouxinan** [comment]
But then there seems to be no point putting isHit in the if condition: it will always be false.
