### ISSUE TITLE
A bug prevents the sanity test from finishing

### ISSUE THREAD

**Issue by zhouxinan** [hungweitseng/CS203-fa21-prefetcher#2]
My understanding of prefetching is that even if there is no prefetching, the sanity test should finish, instead of hang.
However, simply `./cacheSim ./traces/g++.trace` will not finish and will hang forever.

**Comment by zhouxinan** [comment]
After days of investigation, the problem seems to be in the write-buffer's implementation.
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L116
This line 116 invokes `cpu.completeRequest(curr_cycle);` too early. Thus, it should be removed. If we don't,
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L189
This line 189 would set isHit for another cpu request rather than the original write miss. 

After removing `cpu.completeRequest(curr_cycle);` on line 116, `cpu.completeRequest(curr_cycle);` should be re-added after line 193
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L193
in case the write hits in L2, we should finish the request for CPU. 

What's more, when the write misses in L2, the request will be added to queueMem:
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L196

Thus, we should modify:
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L175
to:
`if(req.fromCPU) cpu.completeRequest(curr_cycle);`
so that a write-buffer-initiated write-to-memory can complete the request for CPU.

**Comment by zhouxinan** [comment]
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L136
The `cpu.completeRequest(curr_cycle);` in the above line 136 should also be removed, if the previous fix is to be deployed.

**Comment by akshaygulabrao** [comment]
The bug also shows up on my machine. The program hangs. I let it run for about 30 minutes.

**Comment by zhouxinan** [comment]
Update:
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L136
Line 136 should be changed to:
`if (writeBuffer.add(req,curr_cycle)) { cpu.setStatus(WAITING); }`
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L116
Line 116 should be changed to:
`if (writeBuffer.add(req,curr_cycle)) { cpu.setStatus(WAITING); }`
in order to support the semantics of WAITING status.

**Comment by akshaygulabrao** [comment]
Thank you! How long does g++ take on your machine?

**Comment by zhouxinan** [comment]
> Thank you! How long does g++ take on your machine?

Let's crosscheck the sample prefetcher first. After deploying the above patches, AMAT is 2.113307 and total run time is 1083978 for g++. Is it the same on your side?

**Comment by akshaygulabrao** [comment]
running right now.

**Comment by akshaygulabrao** [comment]
How long did the program(in real life) take to run? I have no idea it is working or stuck in an infinite loop.

**Comment by zhouxinan** [comment]
> How long did the program(in real life) take to run? I have no idea it is working or stuck in an infinite loop.

Within 3 seconds. (If you deploy the patch correctly.)

**Comment by akshaygulabrao** [comment]
well it looks like I didn't write the patch correctly. Let me look again.

**Comment by hungweitseng** [comment]
I don't think the above proposed modification makes sense as it mess up the correct operation for write buffers. It does make the simulator running, but that doesn't mean the behavior is correct.

**Comment by zhouxinan** [comment]
Do you mean that once a request is written to the write buffer, the CPU should complete the request immediately instead of turning to WAITING state?

**Comment by hungweitseng** [comment]
True. Otherwise, you're having the CPU waiting instead of continuing. Shouldn't be the case for write back L2.

**Comment by zhouxinan** [comment]
Then, this line is still incorrect:
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L189
because it is updating a new CPU request's HitL2 status rather than the original write request's HitL2 status.

Maybe the CPU.c can provide an API to let a write-buffer L2 hit to directly increase the hitsL2 count in the CPU.

**Comment by zhouxinan** [comment]
Excuse me, but when will this get fixed?

**Comment by hungweitseng** [comment]
We will not change this as I mentioned in the class. It works fine if you have the sample prefetcher around.

**Comment by akshaygulabrao** [comment]
Wait, really? My code hangs. After adding a print statement for nRequests, my computer hangs on instruction 141231 of testgen.trace. I am using WSL. Perhaps it works if we try the sledge computers??

**Comment by zhouxinan** [comment]
Finally I was able to find out why it would hang.
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L145
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L166
The above two lines mean that the simulator will process queueL2 and queueMem in each cycle. However, the sad fact is that:
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L155
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L175
It may possibly call cpu.completeRequest() for two times in each cycle! Originally, one current request for CPU will correspond to calling cpu.completeRequest() for one time. But here it appeared twice! This can totally mess up CPU.
<img width="721" alt="Screen Shot 2021-11-17 at 12 31 47 PM" src="https://user-images.githubusercontent.com/1636502/142277940-014acbf3-709b-4859-a837-630d4c2b86df.png">
In the above picture, the highlighted part is the CPU state at the stuck point for g++.trace. At the stuck point, the memory queue is processing accessing memory address 2c88870. However CPU's current request address is 2c88c78, which is not the same as 2c88870. The access to 2c88870 is a write (req.load == 0), so 
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L175
The above line will not call complete the request because req.load == 0. Then queueL2, queueMem and writeBuffer are all drained and CPU is stuck at waiting. 
Remedy this will need significant code modification. The easiest way is to treat writeBuffer and queueL2 equally. (Apply the above patch.) 

Let us focus on the prefetching. This change will not significantly affect the fairness and student's grading of the project because:
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L129
Prefetching only focusing on loading rather than writing.

**Comment by akshaygulabrao** [comment]
code does not hang anymore, forgot to move the sample prefetcher into the library so I was using the incomplete prefetcher. Dumb mistake

**Comment by zhouxinan** [comment]
The sample prefetcher works without hanging is due to luckiness because it happens to fetch something that causes the write to hit.
The simulator should always work (not hang) even if with no prefetching logic.

**Comment by akshaygulabrao** [comment]
ooh

**Comment by hungweitseng** [comment]
I have committed a new version that does not hang on my testing machine -- if you still hangs on your side, it's not my issue.
