### ISSUE TITLE
A bug will cause L2 hit rate to be incorrect.

### ISSUE THREAD

**Issue by zhouxinan** [hungweitseng/CS203-fa21-prefetcher#3]
This code line is incorrect:
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L150
Because a pf-initiated request such as 
https://github.com/hungweitseng/CS203-fa21-prefetcher/blob/5e60cfdbec28dbc2dc2be0c8956ea39ecaa87197/main.C#L130
will incorrectly call this line 150 and scramble CPU's hitL2 state. Line 150 should be changed as:
`if (req.fromCPU) cpu.loadHitL2(isHit);`

**Comment by hungweitseng** [comment]
Thanks and updated.
